swiftmailer:
  
    spool: { type: 'memory' }
    transport: smtp
    host:      smtp.mailtrap.io
    username:  username
    password:  password
    auth_mode:  cram-md5
    port: 25 or 465 or 587 or 2525





